import { Inter } from "next/font/google";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-auto w-full">
      <body>{children}</body>
    </html>
  );
}
